import axios from "axios";
import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import CommunityWidget from "../../../components/CommunityWidget";
import Navbar from "../../../components/Navbar";
import Post from "../../../components/Post";
import { CommunityType } from "../../../types/community";
import { PostType } from "../../../types/post";
import subredditLogo from "../../../public/assets/subredditLogo.png";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/router";

const Community: NextPage = () => {
  const router = useRouter();

  const { data: posts, isLoading } = useQuery<PostType[]>(
    ["posts", router.query.community],
    () =>
      axios
        .get(`/api/post?community=${router.query.community}`)
        .then((res) => res.data)
  );

  const { data: community } = useQuery<CommunityType>(
    ["community", router.query.community],
    () =>
      axios
        .get(`/api/community?name=${router.query.community}`)
        .then((res) => res.data[0])
  );

  return (
    <div className="bg-black text-neutral-300 min-h-screen">
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {community && (
        <div className="bg-neutral-900 p-4">
          <div className="max-w-5xl mx-auto flex gap-4 items-center">
            <div className="w-12 h-12 relative">
              <Image src={subredditLogo} layout="fill" alt="" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">
                {community.name[0].toUpperCase() + community.name.substring(1)}
              </h1>
              <h1 className="text-neutral-500">r/{community.name}</h1>
            </div>
          </div>
        </div>
      )}

      <main className="max-w-5xl mx-auto p-4 grid grid-cols-3 gap-4">
        <section className="flex flex-col gap-4 col-span-3 lg:col-span-2">
          {isLoading && (
            <Image
              src="/assets/loading.svg"
              alt="loading"
              width={64}
              height={64}
              priority
            />
          )}
          {posts?.length ? (
            posts?.map((post) => <Post key={post._id} post={post} />)
          ) : (
            <p className="text-neutral-500 text-lg text-center mb-4">
              There are no posts
            </p>
          )}
        </section>
        <section className="row-start-1 lg:row-start-auto col-span-3 lg:col-span-1">
          {community && <CommunityWidget community={community} />}
        </section>
      </main>
    </div>
  );
};

export default Community;
