import React, { MouseEvent, useRef } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { NextPage } from "next";
import { useRouter } from "next/router";
import axios from "axios";
import { useSession } from "next-auth/react";
import CreateBox from "../components/CreateBox";

const CreateCommunity: NextPage = () => {
  const router = useRouter();
  const { data: session } = useSession();
  const textRef = useRef<HTMLInputElement>(null);

  const handleCreate = async (event: MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();

    if (!session) {
      alert("Please log in");
      return;
    }

    if (!textRef.current?.value) {
      alert("Please enter a community name");
      return;
    }

    const response = await axios.post("api/createCommunity", {
      name: textRef.current.value,
      admin: session.user?.name,
    });

    router.push("/");
  };

  return (
    <div className="bg-black text-neutral-300 min-h-screen">
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="max-w-5xl mx-auto p-4 grid grid-cols-3 gap-4">
        <div className="flex flex-col gap-4 col-span-3 lg:col-span-2">
          <div>
            <h1 className="py-4 mb-4 font-bold text-lg border-b border-neutral-700">
              Create a community
            </h1>

            <div className="bg-neutral-900 rounded-md flex flex-col gap-4 p-4">
              <div className="border border-neutral-700 rounded-md w-full flex items-center gap-2">
                <p className="ml-2">r/</p>
                <input
                  ref={textRef}
                  type="text"
                  placeholder="Name"
                  className="bg-transparent p-2 w-full"
                />
              </div>

              <div className="flex justify-end">
                <button
                  onClick={handleCreate}
                  className="bg-gray-100 hover:bg-gray-300 py-1 px-4 rounded-full text-black font-semibold"
                >
                  Create Community
                </button>
              </div>
            </div>
          </div>
        </div>
        <CreateBox />
      </main>
    </div>
  );
};

export default CreateCommunity;
