import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { NextPage } from "next";
import Link from "next/link";
import { MdKeyboardArrowDown } from "react-icons/md";
import { useRouter } from "next/router";
import { compileFunction } from "vm";

const CreatePost: NextPage = () => {
  const [isChooseCommunityOpen, setIsChooseCommunitiesOpen] = useState(false);
  const [communities, setCommunities] = useState<string[]>([
    "r/javascript",
    "r/react",
    "r/nextjs",
  ]);
  const [community, setCommunity] = useState<string>();
  const titleRef = useRef<HTMLInputElement>(null);
  const textRef = useRef<HTMLTextAreaElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const router = useRouter();

  const handleChooseCommunity = (community: string) => {
    setIsChooseCommunitiesOpen(false);
    setCommunity(community);
  };

  const handlePost = () => {
    router.push("/");
  };

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (event.target !== menuRef.current) setIsChooseCommunitiesOpen(false);
    };
    document.body.addEventListener("click", handleClickOutside);
    return () => document.body.removeEventListener("click", handleClickOutside);
  }, []);

  return (
    <div className="bg-black text-neutral-300 min-h-screen">
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="max-w-5xl mx-auto p-4 grid grid-cols-3 gap-4">
        <div className="flex flex-col gap-4 col-span-3 lg:col-span-2">
          <div>
            <h1 className="py-4 mb-4 font-bold text-lg border-b border-neutral-700">
              Create a post
            </h1>
            <div className="select-none">
              <div
                ref={menuRef}
                onClick={() => setIsChooseCommunitiesOpen((prev) => !prev)}
                className="bg-neutral-900 border border-neutral-700 rounded-md my-2 p-2 w-fit font-semibold text-sm flex items-center gap-8 cursor-pointer"
              >
                {community ? <>{community}</> : <>Choose a community</>}
                <MdKeyboardArrowDown className="ml-auto" />
              </div>
              {isChooseCommunityOpen && (
                <div className="absolute overflow-hidden bg-neutral-900 border border-neutral-700 rounded-md max-w-fit text-sm flex flex-col justify-center divide-y divide-neutral-700">
                  {communities.map((community, index) => (
                    <div
                      key={index}
                      onClick={() => handleChooseCommunity(community)}
                      className="p-2 cursor-pointer hover:bg-neutral-800"
                    >
                      {community}
                    </div>
                  ))}
                </div>
              )}
            </div>
            <div className="bg-neutral-900 rounded-md flex flex-col gap-4 p-4">
              <div className="border border-neutral-700 rounded-md w-full">
                <input
                  ref={titleRef}
                  type="text"
                  placeholder="Title"
                  className="bg-transparent p-2 w-full"
                />
              </div>
              <div className="border border-neutral-700 rounded-md w-full">
                <textarea
                  ref={textRef}
                  placeholder="Text"
                  className="bg-transparent p-2 w-full min-h-[8rem]"
                />
              </div>
              <div className="flex justify-end">
                <button
                  onClick={handlePost}
                  className="bg-gray-100 hover:bg-gray-300 py-1 px-4 rounded-full text-black font-semibold"
                >
                  Post
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="hidden lg:flex flex-col justify-center gap-4 bg-neutral-900 border border-neutral-700 rounded-md h-60 p-2">
          <h2 className="font-semibold">Home</h2>
          <p>
            Your personal Reddit frontpage. Come here to check in with your
            favorite communities.
          </p>
          <Link href="create">
            <button className="bg-white bg-opacity-80 hover:bg-opacity-70 text-neutral-900 font-bold rounded-full py-1">
              Create post
            </button>
          </Link>
          <button className="bg-white bg-opacity-0 hover:bg-opacity-5 border font-bold rounded-full py-1">
            Create community
          </button>
        </div>
      </main>
    </div>
  );
};

export default CreatePost;
