import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import HomeWidget from "../components/HomeWidget";
import Navbar from "../components/Navbar";
import Post from "../components/Post";
import { PostType } from "../types/PostType";

export const getServerSideProps = async () => {
  try {
    const response = await axios.get(process.env.NEXTAUTH_URL + "api/getPosts");
    const postsData: PostType[] = response.data;
    return {
      props: { postsData },
    };
  } catch (error) {
    console.log(error);
  }
};

const Home: NextPage<{ postsData: PostType[] }> = ({ postsData }) => {
  return (
    <div className="bg-black text-neutral-300 min-h-screen">
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="max-w-5xl mx-auto p-4 grid grid-cols-3 gap-4">
        <div className="flex flex-col gap-4 col-span-3 lg:col-span-2">
          {postsData?.map((post) => (
            <Post key={post._id} post={post} />
          ))}
        </div>
        <HomeWidget />
      </main>
    </div>
  );
};

export default Home;
